brick_counter/urls.py
from .views import StatsListView, CreateHouse, HouseDetailView, CreateTask
from django.urls import path


app_name = 'brick_counter'
urlpatterns = [
    path('stats/', StatsListView.as_view(), name='stats'),
    path('building/', CreateHouse.as_view(), name='building'),
    path('building/<int:pk>', HouseDetailView.as_view(), name='house_page'),
    path('building/<int:pk>/add_bricks/', CreateTask.as_view(), name='create_task')
]

brick_counter_in_house/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('brick_counter.urls', namespace='brick_counter')),
    path('admin/', admin.site.urls),
]

brick_counter/models.py
from django.db import models
from django.urls import reverse


class House(models.Model):
    address = models.CharField(max_length=100)
    year_of_construction = models.DateField()

    def get_absolute_url(self):
        return reverse('brick_counter:house_page', args=[self.pk])

    class Meta:
        verbose_name = 'Дом'
        verbose_name_plural = 'Дома'
        ordering = ['year_of_construction']

    def __str__(self):
        return self.address


class Task(models.Model):
    number_of_bricks = models.PositiveIntegerField()
    date_and_time = models.DateTimeField()
    house = models.OneToOneField('House',
                                 null=True,
                                 blank=True,
                                 on_delete=models.CASCADE,
                                 verbose_name='Дом для закладки кирпичей')

    class Meta:
        verbose_name = 'Задание на закладку кирпичей'
        verbose_name_plural = 'Задания на закладку кирпичей'
        ordering = ['date_and_time']

    def __str__(self):
        return str(self.number_of_bricks)

brick_counter/forms.py
from django.forms import ModelForm

from .models import House, Task


class HouseForm(ModelForm):
    class Meta:
        model = House
        fields = ('address', 'year_of_construction')


class TaskForm(ModelForm):
    class Meta:
        model = Task
        fields = ('number_of_bricks', 'date_and_time')

brick_counter/views.py
from django.http import HttpResponseRedirect
from .models import House
from django.views.generic import ListView, DetailView, CreateView
from .forms import HouseForm, TaskForm
from django.urls import reverse_lazy


class StatsListView(ListView):
    template_name = 'brick_counter/stats.html'
    model = House
    queryset = House.objects.order_by('-task__date_and_time')
    paginate_by = 10


class HouseDetailView(DetailView):
    model = House
    template_name = 'brick_counter/house_page.html'


class CreateHouse(CreateView):
    template_name = 'brick_counter/building.html'
    form_class = HouseForm

    def form_valid(self, form):
        self.object = form.save()
        return HttpResponseRedirect(reverse_lazy('brick_counter:house_page', args=[self.object.pk]))


class CreateTask(CreateView):
    template_name = 'brick_counter/create_task.html'
    form_class = TaskForm

    def form_valid(self, form):
        house = self.get_initial().get('house')
        self.object = form.save(commit=False)
        self.object.house = house
        self.object.save()
        return HttpResponseRedirect(reverse_lazy('brick_counter:house_page', args=[house.pk]))

    def get_initial(self, *args, **kwargs):
        initial = super(CreateTask, self).get_initial(**kwargs)
        house = int(self.request.path.split('/')[2])
        house = House.objects.get(pk=house)
        initial['house'] = house
        return initial

brick_counter/templates/brick_counter/base_page.html
<!doctype html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>
        {% block title %}
        {% endblock %}
    </title>
  </head>
  <body>
    {% block content %}
    {% endblock %}
  </body>
</html>

brick_counter/templates/brick_counter/building.html
{% extends "brick_counter/base_page.html" %}

{% block title %}
    Создание дома
{% endblock %}

{% block content %}
    <form action="{% url 'brick_counter:building' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Create">
    </form>
    {% include "brick_counter/return_to_main_page.html" %}
{% endblock %}

brick_counter/templates/brick_counter/create_task.html
{% extends "brick_counter/base_page.html" %}

{% block title %}
    Создание задачи
{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Create">
    </form>
    {% include "brick_counter/return_to_main_page.html" %}
{% endblock %}

brick_counter/templates/brick_counter/house_page.html
{% extends "brick_counter/base_page.html" %}

{% block title %}
    Информация о доме
{% endblock %}


{% block content %}
    <h2>{{ house.address }}</h2>
    <div>
        <div>
            <p>
                Год постройки - {{ house.year_of_construction }}
            </p>
        </div>
        {% if house.task %}
        <div>
            <p>
                Количество кирпичей в доме - {{ house.task.number_of_bricks }}
            </p>
            <p>
                Время закладки кирпичей в дом - {{ house.task.date_and_time }}
            </p>
        </div>
        {% else %}
        <div>
            <a href="{% url 'brick_counter:create_task' house.pk %}">
                <p>
                    Положить кирпичи в дом
                </p>
            </a>
        </div>
        {% endif %}
    </div>
    {% include "brick_counter/return_to_main_page.html" %}
{% endblock %}

brick_counter/templates/brick_counter/return_to_main_page.html
    <div>
        <a href="{% url 'brick_counter:stats' %}">
            <p>
                Вернуться на главную страницу
            </p>
        </a>
    </div>

brick_counter/templates/brick_counter/stats.html
{% extends "brick_counter/base_page.html" %}

{% block title %}
    Дом и кирпичи в нем
{% endblock %}

{% block content %}
    <h1>Статистика по домам</h1>
    {% for house in house_list %}
        <div>
            <a href="{% url 'brick_counter:house_page' house.pk %}">
                <p>
                    {{ house.address }} - {{ house.year_of_construction }}
                </p>
            </a>
        </div>
        <div>
            <p>
                Количество кирпичей  доме - {{ house.task }}
            </p>
            <p>
                Дата и время закладки кирпичей в дом - {{ house.task.date_and_time }}
            </p>
        </div>
        <hr>
    {% endfor %}
    <div>
        <a href="{% url 'brick_counter:building' %}">
            <p>
                Создать дом
            </p>
        </a>
    </div>
{% endblock %}